name: "Draft"

on:
  pull_request:
    paths:
      - ".*.sch"
      - ".*.kicad_pcb"
      - ".kibot/*.kibot.yaml"
      - ".github/workflows/*.yml"

env:
  # set this to your kicad project name
  Project: ${{ github.event.repository.name }}
  # Set this to your local timezone. See https://www.wikiwand.com/en/List_of_tz_database_time_zones for valid strings.
  Timezone: UTC
  # Set this to the output folder for all of the generated files.
  # Unless you have a very good reason to change this you should leave it as KiBotOutput.
  OutputFolder: KiBotOutput

jobs:
  Kibot:
    runs-on: ubuntu-latest

    # These are all the steps that generate the files.
    steps:
      # Check out the files
      - uses: actions/checkout@v2

      # Get the commit hash.
      - name: Get GitHub commit hash
        id: get_version
        run: echo "::set-output name=version::$(git rev-parse --short HEAD)"
      # Get the current date and time, in the timezone specified above, for use later.
      - name: Get current date and time
        id: get_date
        run: echo "::set-output name=date::$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d %T')"

      # do string replacement in schematic files
      - name: Set schematic version
        uses: jacobtomlinson/gha-find-replace@v1
        with:
          include: ".*.sch"
          find: "%%version%%"
          replace: ${{ steps.get_version.outputs.version }}
      - name: Set schematic date
        uses: jacobtomlinson/gha-find-replace@v1
        with:
          include: ".*.sch"
          find: "%%date%%"
          replace: 'date "${{ steps.get_date.outputs.date }}"'

      # do string replacement in design files
      - name: Set PCB version
        uses: jacobtomlinson/gha-find-replace@v1
        with:
          include: ".*.kicad_pcb"
          find: "%%version%%"
          replace: ${{ steps.get_version.outputs.version }}
      - name: Set PCB date in page settings
        uses: jacobtomlinson/gha-find-replace@v1
        with:
          include: ".*.kicad_pcb"
          find: "date %%date%%"
          replace: 'date "${{ steps.get_date.outputs.date }}"'
      - name: Set PCB date on PCB layers
        uses: jacobtomlinson/gha-find-replace@v1
        with:
          include: ".*.kicad_pcb"
          find: "%%date%%"
          replace: ${{ steps.get_date.outputs.date }}

      # Actually run KiBot to generate all the files.
      - name: Generate documentation files
        uses: INTI-CMNB/KiBot@master
        if: ${{ success() }}
        with:
          config: .kibot/documentation.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: ${{ env.Project }}.sch
          board: ${{ env.Project }}.kicad_pcb

      # Archive all the artifacts from output and attach to the action's results.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.Project }}-${{ steps.get_version.outputs.version }}-draft
          path: ${{ env.OutputFolder }}/**
