# SPDX-FileCopyrightText: 2022 nerdyscout <https://github.com/nerdyscout/>
#
# SPDX-License-Identifier: CC0-1.0

name: KiBot

on:
  push:
    paths:
      - "pcb/*.kicad_sch"
      - "pcb/*.kicad_pcb"
      - "pcb/*.kicad_pro"
      - ".kibot/*"
      - ".github/workflows/kibot.yml"
  pull_request:
    paths:
      - "pcb/*.kicad_sch"
      - "pcb/*.kicad_pcb"
      - "pcb/*.kicad_pro"
      - ".kibot/*"
      - ".github/workflows/kibot.yml"

env:
  schema: "pcb/*.kicad_sch"
  board: "pcb/*.kicad_pcb"
  dir: "pcb/"

jobs:
# checks
  ERC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@master
        with:
          config: .kibot/erc.kibot.yaml
          schema: ${{ env.schema }}
          board: ${{ env.board }}
          dir: ${{ env.dir }}
  DRC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@master
        with:
          config: .kibot/drc.kibot.yaml
          schema: ${{ env.schema }}
          board: ${{ env.board }}
          dir: ${{ env.dir }}
# documentation
  docs:
    runs-on: ubuntu-latest
    needs: [ERC]
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@master
        with:
          config: .kibot/docs.kibot.yaml
          schema: ${{ env.schema }}
          board: ${{ env.board }}
          dir: ${{ env.dir }}
      - uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: ${{ github.event.repository.name }}_docs
          path: ${{ env.dir }}/docs/**
# fabrications
  gerbers:
    runs-on: ubuntu-latest
    needs: [DRC]
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@master
        with:
          config: .kibot/gerbers.kibot.yaml
          schema: ${{ env.schema }}
          board: ${{ env.board }}
          dir: ${{ env.dir }}
      - uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: ${{ github.event.repository.name }}_gerbers
          path: ${{ env.dir }}/gerbers/**
# cad
  cad:
    runs-on: ubuntu-latest
    needs: [DRC]
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@master
        with:
          config: .kibot/cad.kibot.yaml
          schema: ${{ env.schema }}
          board: ${{ env.board }}
          dir: ${{ env.dir }}
      - uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: ${{ github.event.repository.name }}_cad
          path: ${{ env.dir }}/cad/**
# render
  render:
    runs-on: ubuntu-latest
    needs: [DRC]
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@master
        with:
          config: .kibot/render.kibot.yaml
          schema: ${{ env.schema }}
          board: ${{ env.board }}
          dir: ${{ env.dir }}
      - uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: ${{ github.event.repository.name }}_img
          path: ${{ env.dir }}/img/**
